dist: xenial
language: python
python:
  - "2.7"
node_js:
  '11'
services:
  docker
env:
  global:
  - DOCKER_REPO=hackers-news-search-client/docker_image
  - EB_REGION="ap-southeast-2"
  # - secure: travis Encrypted AWS_ACCOUNT_ID
  # - secure: travis Encrypted AWS_ACCESS_KEY_ID
  # - secure: travis Encrypted AWS_SECRET_ACCESS_KEY
cache:
  directories:
    - "node_modules"
jobs:  
  include:   
    # - stage: "Compile"
    #   node_js: 
    #     '11'
    #   script: npm run build
    # - stage: "Test"
    #   node_js: 
    #     '11'
    #   script: npm run test
    - stage: "Deploy To ECR"
      node_js:
        '11'
      script: >-
        pip install awscli &&
        export PATH=$PATH:$HOME/.local/bin &&
        npm run docker-local-build-travis &&
        bash deploy.sh
  




# script:
#   - npm run test

# after_success:
  # - npm pack

# deploy:
  # - provider: pages
  #   skip_cleanup: true
  #   local_dir: docs/
  #   github_token: $GITHUB_TOKEN
  #   on:
  #     tags: true
  # - provider: releases
  #   api_key: $GITHUB_TOKEN
  #   file_glob: true
  #   file: "{YOURLIB}-*.tgz"
  #   skip_cleanup: true
  #   on:
  #     tags: true
  # - provider: npm
  #   skip_cleanup: true
  #   email: "youremail@example.com"
  #   api_key: $NPM_TOKEN
  #   on:
  #     tags: true