dist: xenial
language: node_js
node_js:
  - '6'
  - '8'
  - '10'
  - '11'
cache:
  directories:
    - "node_modules"  
jobs:
  include:
    - stage: "Install"
      script: npm install
    - stage: "Compile"
      script: npm run build
    - stage: test
      script: npm run test
# script:
#   - npm run test

# after_success:
  # - npm pack

# deploy:
  # - provider: pages
  #   skip_cleanup: true
  #   local_dir: docs/
  #   github_token: $GITHUB_TOKEN
  #   on:
  #     tags: true
  # - provider: releases
  #   api_key: $GITHUB_TOKEN
  #   file_glob: true
  #   file: "{YOURLIB}-*.tgz"
  #   skip_cleanup: true
  #   on:
  #     tags: true
  # - provider: npm
  #   skip_cleanup: true
  #   email: "youremail@example.com"
  #   api_key: $NPM_TOKEN
  #   on:
  #     tags: true