dist: xenial
language: node_js
cache:
  directories:
    - "node_modules"  
jobs:
  include:   
    - stage: "Compile"
      node_js: 
        '11'
      script: npm run build
    - stage: "Test"
      node_js: 
        '11'
      script: npm run test
# script:
#   - npm run test

# after_success:
  # - npm pack

# deploy:
  # - provider: pages
  #   skip_cleanup: true
  #   local_dir: docs/
  #   github_token: $GITHUB_TOKEN
  #   on:
  #     tags: true
  # - provider: releases
  #   api_key: $GITHUB_TOKEN
  #   file_glob: true
  #   file: "{YOURLIB}-*.tgz"
  #   skip_cleanup: true
  #   on:
  #     tags: true
  # - provider: npm
  #   skip_cleanup: true
  #   email: "youremail@example.com"
  #   api_key: $NPM_TOKEN
  #   on:
  #     tags: true